apiVersion: apps/v1 # the app/v1 is the apropriate for Deployments
kind: Deployment # indicating that this configuration file is defining a Deployment
metadata:
  name: app2-com # The deployment name
  labels:
    app: app2-com
spec: # This section defines the desired state of the Deployment
  replicas: 3
  selector:
    matchLabels:
      app: app2-com
  template:
    metadata:
      labels:
        app: app2-com # indicate the label of the pods will be created using this template
    spec:
      containers:
      - name: app2-com # Assigns a name to the container
        image: holysemicolon/uwu-nginx:1.0 # Docker image to use for this container
        ports: # Defines the ports to open in the container
        - containerPort: 80 # dicates that the container will listen on port 80
