

Vagrant.configure("2") do |config|

  config.vm.define "Testing Machine" do |master|
    master.vm.box = "generic/centos7"
    master.vm.network :private_network, ip: "192.168.56.110"
    master.vm.synced_folder ".", "/vagrant"
    master.vm.provider "virtualbox" do |v|
      v.name = "part 2"
      v.memory = "1024"
      v.cpus = "2"
    end
    master.vm.provision 'shell', path: "scripts/install_k3s.sh"
  end

end
