Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"

  # config.vm.network "private_network", ip: "192.168.56.110" # read more about this one in the network page (vagrant docs)

  config.vm.define "mbariS" do |master|
    master.vm.hostname = "mbariS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |v|
      v.name = "mbariS"
      v.memory = "1024"
      v.cpus = "2"
    end
    master.vm.provision 'shell', path: "scripts/k3s_installer_as_master.sh"
  end

  config.vm.define "mbariSW" do |worker|
    worker.vm.hostname = "mbariSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.name = "mbariSW"
      v.memory = "1024"
      v.cpus = "2"
    end
    # worker.vm.provision 'shell', path: "scripts/k3s_installer_as_master.sh"
  end

end
